[package]
name = "webserver"
version = "0.1.0"
authors = ["julian <julianMBP>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.1"
colored = "1.9.3"
#rouille
rouille = "0.1.7"
chrono = "0.4"